### ISSUE TITLE
All ingresses are reported as 404 by IMC

### ISSUE THREAD

**Issue by vfiset** [stakater/IngressMonitorController#221]
Hi, running IMC `1.0.47` installed with the official stable helm chart `1.0.48` on gke. 

I am getting `404`s on all my ingresses in the IMC logs but when I install curl on the pod then I curl the same urls I am getting results ...

Am I missing something?

```
$ kubectl logs ingressmonitorcontroller-7ff9976f4d-kz8n5
2020/01/03 19:36:40 Warning: KUBERNETES_NAMESPACE is unset, will monitor ingresses in all namespaces.
2020/01/03 19:36:40 Reading YAML Configuration
2020/01/03 19:36:40 Starting Ingress Monitor controller
2020/01/03 19:36:40 Monitor Name: default-metrics-auth
2020/01/03 19:36:40 Monitor URL: https://metrics.example.com/oauth2/ping
2020/01/03 19:36:40 GetByName Request failed for name: default-metrics-auth. Status Code: 404
2020/01/03 19:36:41 AddMonitor Request failed. Status Code: 404
2020/01/03 19:36:41 Monitor Name: default-xx
2020/01/03 19:36:41 Monitor URL: http://xx-v2.example.com/
2020/01/03 19:36:41 GetByName Request failed for name: default-xx. Status Code: 404
2020/01/03 19:36:41 AddMonitor Request failed. Status Code: 404
2020/01/03 19:36:41 Pod has 2 containers so skipping health endpoint
2020/01/03 19:36:41 Monitor Name: default-metrics
2020/01/03 19:36:41 Monitor URL: https://metrics.example.com/
2020/01/03 19:36:41 GetByName Request failed for name: default-metrics. Status Code: 404
2020/01/03 19:36:42 AddMonitor Request failed. Status Code: 404

$ kubectl exec -it ingressmonitorcontroller-7ff9976f4d-kz8n5 ash
/ # apk add curl
OK: 6 MiB in 15 packages
/ # curl -I https://metrics.example.com/
HTTP/1.1 302 Moved Temporarily
Server: openresty/1.15.8.2
Date: Fri, 03 Jan 2020 19:52:17 GMT
Content-Type: text/html
Content-Length: 151
Connection: keep-alive
Strict-Transport-Security: max-age=15724800; includeSubDomains
Location: https://metrics.example.com/oauth2/start?rd=%2F

/ # curl -I https://metrics.example.com/oauth2/ping
HTTP/1.1 403 Forbidden
Server: openresty/1.15.8.2
Date: Fri, 03 Jan 2020 19:52:31 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
```

**Comment by usamaahmadkhan** [comment]
@vfiset can you share the manifests and provider config you are using?

**Comment by vfiset** [comment]
Hi @usamaahmadkhan. I use pretty much the vanilla config from the stable helm chart:
```
resource "helm_release" "ingressmonitorcontroller" {
  name  = "ingressmonitorcontroller"
  chart = "stable/ingressmonitorcontroller"
  namespace = "default"

  set {
    name  = "name"
    value = "UptimeRobot"
  }

  set {
    name  = "apiKey"
    value = "xx"
  }

  set {
    name  = "apiURL"
    value = "https://api.uptimerobot.com/v2/"
  }

  set {
    name  = "alertContacts"
    value = "xx"
  }

  set {
    name  = "creationDelay"
    value = "300s"
  }

  depends_on = [helm_release.default-nginx-ingress]

}
```

which manifests are you interested in ?

**Comment by usamaahmadkhan** [comment]
@vfiset as the stable repository is being depricated. We dont maintain it anymore. The new home for ingressmonitorcontroller charts is `https://stakater.github.io/stakater-charts/`. Are you facing this issue  with the latest release as well?

**Comment by vfiset** [comment]
oops! my bad did not realize that.

I am not facing the same issue but something else:

```
$ kubectl logs ingressmonitorcontroller-6cfd778d6-9t6cv
2020/01/06 15:39:24 Warning: KUBERNETES_NAMESPACE is unset, will monitor ingresses in all namespaces.
2020/01/06 15:39:24 Reading YAML Configuration
2020/01/06 15:39:24 Starting Ingress Monitor controller
2020/01/06 15:39:24 Monitor Name: default-blabla
2020/01/06 15:39:24 Monitor URL: http://xx.example.com/blabla
E0106 15:39:24.245844       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:509
/usr/local/go/src/runtime/panic.go:491
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:367
/go/src/github.com/stakater/IngressMonitorController/pkg/http/httpClient.go:38
/go/src/github.com/stakater/IngressMonitorController/pkg/http/httpClient.go:50
/go/src/github.com/stakater/IngressMonitorController/pkg/monitors/uptimerobot/uptime-monitor.go:34
/go/src/github.com/stakater/IngressMonitorController/pkg/monitors/monitor-proxy.go:42
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:182
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:177
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/actions.go:51
<autogenerated>:1
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:121
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:105
/go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:97
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xee41c9]

goroutine 35 [running]:
github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x111
panic(0x1000000, 0x190d590)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/stakater/IngressMonitorController/pkg/http.(*HttpClient).postWithHeaders(0xc42012d988, 0xc42011a2c0, 0x3a, 0xc42012d710, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/stakater/IngressMonitorController/pkg/http/httpClient.go:38 +0x129
github.com/stakater/IngressMonitorController/pkg/http.(*HttpClient).PostUrlEncodedFormBody(0xc42012d988, 0xc42011a2c0, 0x3a, 0xc4202b5d90, 0xc, 0x113c60c, 0x1b)
        /go/src/github.com/stakater/IngressMonitorController/pkg/http/httpClient.go:50 +0x17c
github.com/stakater/IngressMonitorController/pkg/monitors/uptimerobot.(*UpTimeMonitorService).GetByName(0xc4203f2b40, 0xc42026f680, 0xb, 0x49, 0xc42012dbd8, 0x4299e6)
        /go/src/github.com/stakater/IngressMonitorController/pkg/monitors/uptimerobot/uptime-monitor.go:34 +0x12f
github.com/stakater/IngressMonitorController/pkg/monitors.(*MonitorServiceProxy).GetByName(0xc42012dc68, 0xc42026f680, 0xb, 0xc420305100, 0xc42007f528, 0xc42012dbe8)
        /go/src/github.com/stakater/IngressMonitorController/pkg/monitors/monitor-proxy.go:42 +0x48
github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).createOrUpdateMonitor(0xc4202163c0, 0xc4202b5d70, 0xb, 0x18aaca0, 0xc4203f2b40, 0xc42026f680, 0xb, 0xc42026f680, 0xb, 0xc42031a330, ...)
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:182 +0x5a
github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).createOrUpdateMonitors(0xc4202163c0, 0xc42026f680, 0xb, 0xc42026f680, 0xb, 0xc42031a330, 0x27, 0xc4202c4120)
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:177 +0xbc
github.com/stakater/IngressMonitorController/pkg/controller.ResourceUpdatedAction.handle(0x1117920, 0xc4204ae580, 0x0, 0x0, 0xc4202163c0, 0xc42013fe10, 0xa0072242200)
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/actions.go:51 +0x3a4
github.com/stakater/IngressMonitorController/pkg/controller.(*ResourceUpdatedAction).handle(0xc4201322c0, 0xc4202163c0, 0xc4201322c0, 0x7f366dc74938)
        <autogenerated>:1 +0x61
github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).processNextItem(0xc4202163c0, 0x84f200)
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:121 +0xdb
github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).runWorker(0xc4202163c0)
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:105 +0x2b
github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).(github.com/stakater/IngressMonitorController/pkg/controller.runWorker)-fm()
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:97 +0x2a
github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4203233b0)
        /go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x5e
github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4203233b0, 0x3b9aca00, 0x0, 0x2020200a7b203a01, 0xc4202a41e0)
        /go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4203233b0, 0x3b9aca00, 0xc4202a41e0)
        /go/src/github.com/stakater/IngressMonitorController/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/stakater/IngressMonitorController/pkg/controller.(*MonitorController).Run
        /go/src/github.com/stakater/IngressMonitorController/pkg/controller/controller.go:97 +0x1dc
```

**Comment by vfiset** [comment]
the only change from my original post is:
```
  # helm_release.ingressmonitorcontroller will be updated in-place
  ~ resource "helm_release" "ingressmonitorcontroller" {
      ~ chart            = "stable/ingressmonitorcontroller" -> "stakater/ingressmonitorcontroller"
```

**Comment by usamaahmadkhan** [comment]
@vfiset We pass the config in configMaps as a string. with the key being `data`. in helm terms, the config exist at `.Values.ingressMonitorController.data.config.yaml` as a string value.  My guess is the values you are setting are not being set at the right level. Can you provide me the output of this command? Check the output of this command:
 `kubectl get configmap ingressmonitorcontroller -n default -o yaml`
It should have the correct values you are trying to set in your helm_release module

**Comment by vfiset** [comment]
You were right @usamaahmadkhan ! by switching to config into the data.config section it works !
``` 
ingressMonitorController:
  data:
    config.yaml: |-
      providers:
      - name: UptimeRobot
        apiKey: xx
        apiURL: https://api.uptimerobot.com/v2/
        alertContacts: xx
      enableMonitorDeletion: true
      monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
      # how often (in seconds) monitors should be synced to their Kubernetes resources (0 = disabled)
      resyncPeriod: 0
      # creationDelay is a duration string to add a delay before creating new monitor (e.g., to allow DNS to catch up first)
      # https://golang.org/pkg/time/#ParseDuration
      creationDelay: 300s
```

thanks for the support!
